const languages = ["English", "Romanian", "Hungarian", "German", "French", "Dutch"];
const technologies = [
    ".NET",
    "C#",
    "C++",
    "C",
    "Rust",
    "Go",
    "Typescript",
    "Javascript",
    "HTML",
    "CSS",
    "Python",
    "Java",
    "Ruby",
    "Swift",
    "Kotlin",
    "PHP",
    "Scala",
    "Perl",
    "Haskell",
    "Elixir",
    "Dart",
    "Objective-C",
    "SQL",
    "R",
    "MATLAB",
    "React.js",
    "Next.js",
    "Svelte",
    "Vue.js",
    "Flutter",
    "Node.js",
    "Django",
    "Flask",
    "MongoDB",
    "GraphQL",
];

export { technologies, languages };
